### ISSUE TITLE
2 dropdown is not working on one page

### ISSUE THREAD

**Issue by lemonyellow78** [pecuchet/multi-select#2]
2 dropdown is not working on one page

how to Solve this issue?

please help me for solve this issue
https://www.lemonyellow.in/clients/pisceser1marine/index.html

**Comment by pecuchet** [comment]
You are right and it's fixed (see https://github.com/dotburo/multi-select/commit/ed14456eb6a51f14182f618a9d4f877142bf718d and the [demo](https://dotburo.github.io/multi-select/))!

Just update the package in your project with `npm update @dotburo/multi-select` and you should be OK.

**Comment by lemonyellow78** [comment]
Thank you for your help;

Again thank you.


Regards,
Nitin Jadhav
UI Developer


Lemon Yellow LLP
We design digital happiness

Kris Korner Plaza, Office no. 7 & 8, 1st Floor, Anand Nagar, Opp. Saraswati
Vidyalaya,
G. B. Road, Thane (West) - 400615, India.
*Tel:* +91 022 25974066  | Ext no :- 24
*Mob:*+919137160963
www.lemonyellow.net
